#include "Arduino.h"

#define TECS_CLUB_NTP_FEATURE
#define TECS_CLUB_WS_FEATURE
#define TECS_CLUB_TASK_FEATURE
#ifdef TECS_CLUB_TASK_FEATURE
	// #define TECS_CLUB_FRESHENER
	#ifdef TECS_CLUB_FRESHENER
		//#define FRESHENER_ESP_32
	#endif
#endif

//#define TECS_CLUB_TIMER_FEATURE
#define TECS_CLUB_WEB_API_FEATURE
#define TECS_CLUB_LED_SHOW_FEATURE
#define TECS_CLUB_KNU_FEATURE
#ifdef TECS_CLUB_KNU_FEATURE
	#define TECS_CLUB_KNU_EVENT_FEATURE
#endif

#define TECS_CLUB_PCA9685_FEATURE
#define TECS_CLUB_MCP23X17_FEATURE

#define TECS_CLUB_ADS1X15_FEATURE
#ifdef TECS_CLUB_ADS1X15_FEATURE
	#define TECS_CLUB_ADS_TASK_FEATURE
	#define TECS_CLUB_ADS_EVENT_FEATURE
	#ifdef TECS_CLUB_ADS_EVENT_FEATURE
		#define TECS_CLUB_SERVO_EVENT_FEATURE
		#ifdef TECS_CLUB_SERVO_EVENT_FEATURE
		#endif
	#endif
#endif

extern void TECS_CLUB_1ST_SETUP();
extern void TECS_CLUB_2ND_SETUP();
